---

# This task is used to create variables used in giving a warning summary for manual tasks
# that need attention
- name: "{{ warn_control_id }} | Set fact for manual task warning."
  set_fact:
    warn_control_list: "{{ warn_control_list }} [{{ warn_control_id }}]"
    warn_count: "{{ warn_count | int + 1 }}"