- name: "3.3 Configure Network Kernel Parameters"
  become: true
  hosts: rhel
  vars_files: 
    - ../../defaults/main.yml
  handlers:
    - import_tasks: ../../handlers/main.yml
  tasks:

    - name: "3.3.1 | Ensure IP forwarding is disabled"
      block:
        - name: "3.3.1 | Ensure IP forwarding is disabled | Disable IPv4 forwarding"
          ansible.posix.sysctl:
              name: net.ipv4.ip_forward
              value: '0'
              ignoreerrors: true
              sysctl_file: "{{ sysctl_file }}"
          notify: sysctl flush ipv4 route table

        - name: "3.3.1 | Ensure IP forwarding is disabled | Disable IPv6 forwarding"
          ansible.posix.sysctl:
              name: net.ipv6.conf.all.forwarding
              value: '0'
              ignoreerrors: true
              sysctl_file: "{{ sysctl_file }}"
          notify: sysctl flush ipv6 route table
          when:
              - ipv6_required or
                ipv6_sysctl_force

    - name: "3.3.2 | Ensure packet redirect sending is disabled"
      ansible.posix.sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        sysctl_set: true
        ignoreerrors: true
        sysctl_file: "{{ sysctl_file }}"
      notify: sysctl flush ipv4 route table
      with_items:
        - { name: net.ipv4.conf.all.send_redirects, value: 0 }
        - { name: net.ipv4.conf.default.send_redirects, value: 0 }

    - name: "3.3.3 | Ensure bogus ICMP responses are ignored"
    ansible.posix.sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: '1'
      state: present
      ignoreerrors: true
      sysctl_file: "{{ sysctl_file }}"
    notify: sysctl flush ipv4 route table

    - name: "3.3.4 | Ensure broadcast ICMP requests are ignored"
      ansible.posix.sysctl:
        name: net.ipv4.icmp_echo_ignore_broadcasts
        value: '1'
        ignoreerrors: true
        sysctl_file: "{{ sysctl_file }}"
      notify: sysctl flush ipv4 route table

    - name: "3.3.5 | Ensure ICMP redirects are not accepted"
      block:
        - name: "3.3.5 | Ensure ICMP redirects are not accepted | Set ICMP redirects IPv4"
          ansible.posix.sysctl:
            name: '{{ item.name }}'
            value: '{{ item.value }}'
            sysctl_set: true
            ignoreerrors: true
            sysctl_file: "{{ sysctl_file }}"
          notify: sysctl flush ipv4 route table
          with_items:
            - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
            - { name: net.ipv4.conf.default.accept_redirects, value: 0 }

        - name: "3.3.5 | Ensure ICMP redirects are not accepted | Set ICMP redirects IPv6"
          ansible.posix.sysctl:
            name: '{{ item.name }}'
            value: '{{ item.value }}'
            sysctl_set: true
            ignoreerrors: true
            sysctl_file: "{{ sysctl_file }}"
          notify: sysctl flush ipv6 route table
          with_items:
            - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
            - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
          when: ipv6_required or ipv6_sysctl_force

    - name: "3.3.6 | Ensure secure ICMP redirects are not accepted"
      ansible.posix.sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        sysctl_set: true
        ignoreerrors: true
        sysctl_file: "{{ sysctl_file }}"
      notify: sysctl flush ipv4 route table
      with_items:
        - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
        - { name: net.ipv4.conf.default.secure_redirects, value: 0 }

    - name: "3.3.7 | Ensure Reverse Path Filtering is enabled"
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_set: true
        ignoreerrors: true
        sysctl_file: "{{ sysctl_file }}"
      loop:
        - net.ipv4.conf.all.rp_filter
        - net.ipv4.conf.default.rp_filter
      notify: sysctl flush ipv4 route table

    - name: "3.3.8 | Ensure source routed packets are not accepted"
      block:
        - name: "3.3.8 | Ensure source routed packets are not accepted | Set routed packets IPv4"
          ansible.posix.sysctl:
            name: '{{ item.name }}'
            value: '{{ item.value }}'
            sysctl_set: true
            ignoreerrors: true
            sysctl_file: "{{ sysctl_file }}"
          notify: sysctl flush ipv4 route table
          with_items:
            - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
            - { name: net.ipv4.conf.default.accept_source_route, value: 0 }

        - name: "3.3.8 | Ensure source routed packets are not accepted | Set routed packets IPv6"
          ansible.posix.sysctl:
            name: '{{ item.name }}'
            value: '{{ item.value }}'
            sysctl_set: true
            ignoreerrors: true
            sysctl_file: "{{ sysctl_file }}"
          notify: sysctl flush ipv6 route table
          with_items:
            - { name: net.ipv6.conf.all.accept_source_route, value: 0}
            - { name: net.ipv6.conf.default.accept_source_route, value: 0 }
          when: ipv6_required or ipv6_sysctl_force

    - name: "3.3.9 | Ensure suspicious packets are logged"
      ansible.posix.sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        sysctl_set: true
        ignoreerrors: true
        sysctl_file: "{{ sysctl_file }}"
      notify: sysctl flush ipv4 route table
      with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 }

    - name: "3.3.10 | PATCH | Ensure TCP SYN Cookies is enabled"
      ansible.posix.sysctl:
        name: net.ipv4.tcp_syncookies
        value: '1'
        sysctl_set: true
        ignoreerrors: true
        sysctl_file: "{{ sysctl_file }}"
      notify: sysctl flush ipv4 route table

    - name: "3.3.11 | Ensure IPv6 router advertisements are not accepted"
      ansible.posix.sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        sysctl_set: true
        ignoreerrors: true
        sysctl_file: "{{ sysctl_file }}"
      notify: sysctl flush ipv6 route table