- name: "3 Protocols and Devices"
  become: true
  hosts: rhel
  vars_files: 
    - ../../defaults/main.yml
  handlers:
    - import_tasks: ../../handlers/main.yml
  tasks:

    - name: "3.1.1 | Verify if IPv6 is enabled on the system"
      block:
          - name: "3.1.1 | Verify if IPv6 is enabled on the system | disable all except localhost"
            ansible.posix.sysctl:
                name: "{{ item }}"
                value: '1'
                sysctl_set: true
                sysctl_file: "{{ sysctl_file }}"
            with_items:
                - net.ipv6.conf.all.disable_ipv6
                - net.ipv6.conf.default.disable_ipv6
                - net.ipv6.conf.lo.disable_ipv6

          - name: "3.1.1 | Verify if IPv6 is enabled on the system | disable localhost sysctl"
            ansible.posix.sysctl:
                name: net.ipv6.conf.lo.disable_ipv6
                value: '1'
                sysctl_set: true
                sysctl_file: "{{ sysctl_file }}"
            notify: change_requires_reboot
            when:
                - ipv6_disable_localhost

          - name: "3.1.1 | PATCH | Verify if IPv6 is enabled on the system | disable localhost /etc/hosts"
            lineinfile:
                path: /etc/hosts
                regexp: '^(::1.*)'
                line: '#\1'
                backrefs: true
            notify: change_requires_reboot
            when:
                - ipv6_disable_localhost

    # - name: "3.1.2 | Ensure wireless interfaces are disabled"
    #   block:
    #     - name: "3.1.2 | Ensure wireless interfaces are disabled | Check if nmcli command is available"
    #       shell: rpm -q NetworkManager
    #       changed_when: false
    #       failed_when: false
    #       check_mode: false
    #       register: nmcli_available

    #     - name: "3.1.2 | Ensure wireless interfaces are disabled | Check if wifi is enabled"
    #       shell: nmcli radio wifi
    #       register: wifi_enabled
    #       changed_when: wifi_enabled.stdout != "disabled"
    #       failed_when: false
    #       when: nmcli_available.rc == 0

    #     - name: "3.1.2 | Ensure wireless interfaces are disabled | Disable wifi if enabled"
    #       shell: nmcli radio all off
    #       changed_when: false
    #       failed_when: false
    #       when: wifi_enabled is changed  # noqa: no-handler

    - name: 3.1.3 | Ensure bluetooth services are not in use
      systemd:
        name: bluetooth
        state: stopped
        enabled: no
    