- name: "3.4.3 IPtables Software "
  become: true
  hosts: rhel
  vars_files: 
    - ../../defaults/main.yml
  handlers:
    - import_tasks: ../../handlers/main.yml
  tasks:

    - name: "3.4.3.1.1 | Ensure iptables packages are installed"
      package:
        name:
          - " {{ packages_present[2] }} "
          - " {{ packages_present[3] }} "
        state: present

    
    - name: "3.4.3.1.2 | Ensure nftables is not installed with iptables"
      package:
        name: " {{ packages_absent[29] }} "
        state: absent

    - name: "3.4.3.1.3 | Ensure firewalld is either not installed or masked with iptables"
      package:
        name: " {{ packages_absent[30] }} "
        state: absent