- name: "5.2.2.x Data Retention "
  become: true
  hosts: rhel
  vars_files: 
    - ../../defaults/main.yml
  vars:
    file: 
      /etc/audit/auditd.conf
  handlers:
    - import_tasks: ../../handlers/main.yml
  tasks:

    - name: "5.2.2.1 | Ensure audit log storage size is configured"
      lineinfile:
        path: "{{ file }}"
        regexp: "^max_log_file( |=)"
        line: "max_log_file = {{ max_log_file_size }}"
      notify: restart auditd

    - name: "5.2.2.2 | Ensure audit logs are not automatically deleted"
      lineinfile:
        path: "{{ file }}"
        regexp: "^max_log_file_action"
        line: "max_log_file_action = {{ cis_auditd['max_log_file_action'] }}"
      notify: restart auditd

    - name: "5.2.2.3 | Ensure system is disabled when audit logs are full"
      lineinfile:
        path: "{{ file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      notify: restart auditd
      with_items:
        - { regexp: '^admin_space_left_action', line: 'admin_space_left_action = {{ cis_auditd.admin_space_left_action }}' }
        - { regexp: '^action_mail_acct', line: 'action_mail_acct = {{ cis_auditd.action_mail_acct }}' }
        - { regexp: '^space_left_action', line: 'space_left_action = {{ cis_auditd.space_left_action }}' }

    - name: "5.2.2.4 Ensure system warns when audit logs are low on space "
      block:

        - name: space_left_action
          lineinfile:
            path: "{{ file }}"
            regexp: '^space_left_action'
            line: 'space_left_action = email'
          
        - name: admin_space_left_action
          lineinfile:
            path: "{{ file }}"
            regexp: '^admin_space_left_action'
            line: 'admin_space_left_action = halt'
      notify: restart auditd