- name: "5.1.1.x | Configure rsyslog"
  become: true
  hosts: rhel
  vars_files: 
    - ../../defaults/main.yml
  vars:
    file: 
      - /etc/rsyslog.conf
  handlers:
    - import_tasks: ../../handlers/main.yml
  tasks:

    - name: "5.1.1.1 | Ensure rsyslog installed"
      package:
        name: "{{ packages_present[6] }} "
        state: present

    - name: "5.1.1.2 | Ensure rsyslog Service is enabled"
      service:
        name: "{{ services[5] }}"
        enabled: true

    - name: "5.1.1.3 | Ensure journald is configured to send logs to rsyslog"
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: "^#ForwardToSyslog=|^ForwardToSyslog="
        line: ForwardToSyslog=yes

    - name: "5.1.1.4 | Ensure rsyslog default file permissions configured"
      lineinfile:
        path: "{{ file[0] }}"
        regexp: '^\$FileCreateMode'
        line: '$FileCreateMode 0640'
      notify: restart rsyslog

    - name: "5.`.1.5 | Ensure logging is configured"
      block:
        - name: "5.1.1.5 | Ensure logging is configured | rsyslog current config message out"
          shell: cat /etc/rsyslog.conf
          changed_when: false
          failed_when: false
          check_mode: false
          register: audit

        - name: "5.1.1.5 | Ensure logging is configured | rsyslog current config message out"
          debug:
            msg:
              - "These are the current logging configurations for rsyslog, please review:"
              - "{{ audit.stdout_lines }}"

        - name: "5.1.1.5 | Ensure logging is configured | mail.* log setting"
          blockinfile:
            path: "{{ file[0] }}"
            marker: "# {mark} MAIL LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
              # mail logging additions to meet CIS standards
              mail.*                                                  -/var/log/mail
              mail.info                                               -/var/log/mail.info
              mail.warning                                            -/var/log/mail.warning
              mail.err                                                /var/log/mail.err
            insertafter: '# Log all the mail messages in one place.'
          notify: restart rsyslog
          when: rsyslog_ansiblemanaged

        - name: "5.1.1.5 | Ensure logging is configured | news.crit log setting"
          blockinfile:
            path: "{{ file[0] }}"
            state: present
            marker: "# {mark} NEWS LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
              # news logging additions to meet CIS standards
              news.crit                                               -/var/log/news/news.crit
              news.notice                                             -/var/log/news/news.crit
            insertafter: '# Save news errors of level crit and higher in a special file.'
          notify: restart rsyslog
          when: rsyslog_ansiblemanaged

        - name: "5.1.1.5 | Ensure logging is configured | Misc. log setting"
          blockinfile:
            path: "{{ file[0] }}"
            state: present
            marker: "# {mark} MISC. LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
              # misc. logging additions to meet CIS standards
              *.=warning;*.=err                                        -/var/log/warn
              *.crit                                                   /var/log/warn
              *.*;mail.none;news.none                                  /var/log/messages
            insertafter: '#### RULES ####'
          notify: restart rsyslog
          when: rsyslog_ansiblemanaged

        - name: "5.1.1.5 | Ensure logging is configured | Local log settings"
          blockinfile:
            path: "{{ file[0] }}"
            state: present
            marker: "#{mark} LOCAL LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
              # local log settings to meet CIS standards
              local0,local1.*                                          -/var/log/localmessages
              local2,local3.*                                          -/var/log/localmessages
              local4,local5.*                                          -/var/log/localmessages
              local6,local7.*                                          -/var/log/localmessages
              *.emrg                                                    :omusrmsg:*
            insertafter: '#### RULES ####'
          notify: restart rsyslog

        - name: "5.1.1.5 | Ensure logging is configured | Auth Settings"
          blockinfile:
            path: "{{ file[0] }}"
            state: present
            marker: "#{mark} Auth SETTINGS (ANSIBLE MANAGED)"
            block: |
              # Private settings to meet CIS standards
              auth,authpriv.*                                          -/var/log/secure
            insertafter: '#### RULES ####'
          notify: restart rsyslog

        - name: "5.1.1.5  | Ensure logging is configured | Cron Settings"
          blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "#{mark} Cron SETTINGS (ANSIBLE MANAGED)"
            block: |
              # Cron settings to meet CIS standards
              cron.*                                                   /var/log/cron
            insertafter: '#### RULES ####'
          notify: restart rsyslog

    # - name: "5.1.1.6 | Ensure rsyslog is configured to send logs to a remote log host"
    #   blockinfile:
    #     path: " {{ file[0] }}"
    #     state: present
    #     block: |
    #       # remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
    #       *.* @@{{ remote_log_server }}
    #     insertafter: EOF
    #   register: result
    #   failed_when:
    #     - result is failed
    #     - result.rc != 257
    #   notify: restart rsyslog  

    - name: "5.1.1.7 | Ensure rsyslog is not configured to recieve logs from a remote client"
      block:
        - name: "5.1.1.7 | Ensure rsyslog is not configured to recieve logs from a remote client. | When not log host"
          replace:
            path: "{{ file[0] }}"
            regexp: '({{ item }})'
            replace: '#\1'
          notify: restart rsyslog
          with_items:
            - '^(\$ModLoad imtcp)'
            - '^(\$InputTCPServerRun)'
            - '^(module\(load="imtcp"\))'
            - '^(input\(type="imtcp")'
          when: not system_is_log_server

        - name: "5.1.1.7 | Ensure rsyslog is not configured to recieve logs from a remote clients. | When log host"
          replace:
            path: " {{ file[0] }}"
            regexp: '^#(.*{{ item }}.*)'
            replace: '\1'
          notify: restart rsyslog
          with_items:
            - 'ModLoad imtcp'
            - 'InputTCPServerRun'
            - 'module\(load="imtcp"\)'
            - 'input\(type="imtcp"'
          when: system_is_log_server