- name: "5.1 | Configure logging"
  become: true
  hosts: rhel
  vars_files: 
    - ../../defaults/main.yml
  vars:
    file:
      - /etc/crontab
      - /etc/cron.hourly
      - /etc/cron.daily
      - /etc/cron.weekly
      - /etc/cron.monthly
      - /etc/cron.d
      - /etc/cron.deny
      - /etc/cron.allow
      - /etc/at.deny
      - /etc/at.allow
  handlers:
    - import_tasks: ../../handlers/main.yml
  tasks:

    - name: "4.1.1.1 | Ensure cron daemon is enabled"
      service:
        name: "{{ services[6] }}"
        enabled: true

    - name: "4.1.1.2 | Ensure permissions on /etc/crontab are configured"
      file:
        path: "{{ file[0] }}"
        owner: root
        group: root
        mode: 0600

    - name: "4.1.1.3 - 4.1.1.7 | Ensure cron files are configured"
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0700
      with_items:
        - "{{ file[1] }}"
        - "{{ file[2] }}"
        - "{{ file[3] }}"
        - "{{ file[4] }}"
        - "{{ file[5] }}"

    - name: "4.1.1.8 | Ensure cron is restricted to authorized users"
      block:
        - name: "4.1.1.8 | Ensure cron is restricted to authorized users | Remove cron.deny"
          file:
            path: "{{ file[6] }}"
            state: absent

        - name: "4.1.1.8 | Ensure cron is restricted to authorized users | Check if cron.allow exists"
          stat:
            path: "{{ file[7] }}"
          register: cron_allow_state

        - name: "4.1.1.8 | Ensure cron is restricted to authorized users | Ensure cron.allow is restricted to authorized users"
          file:
            path: "{{ file[7] }}"
            state: '{{ "file" if cron_allow_state.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: 0600
      
    - name: "5.1.2.1 | Ensure at is restricted to authorized users"
      block:
        - name: "5.1.2.1 | Ensure at is restricted to authorized users | Remove at.deny"
          file: 
            path: "{{ file[8] }}"
            state: absent

        - name: "5.1.2.1 | Ensure at is restricted to authorized users  | Check if at.allow exists"
          stat:
            path: "{{ file[9] }}"
          register: at_allow_state

        - name: "5.1.2.1 | Ensure at is restricted to authorized users | Ensure at.allow is restricted to authorized users"
          file:
            path: "{{ file[9] }}"
            state: '{{ "file" if at_allow_state.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: 0600