- name: Gnome Display Manager
  become: true
  hosts: rhel
  vars_files: 
    - ../../defaults/main.yml
  handlers:
    - import_tasks: ../../handlers/main.yml
  tasks:

    - name: "1.8.1 | Ensure GNOME Display Manager is removed"
      package:
        name: "{{ packages_absent[0] }}"
        state: absent

    - name: "1.8.2 | Ensure GDM login banner is configured"
      lineinfile:
        path: "{{ item.file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: true
        owner: root
        group: root
        mode: 0644
      notify: reload dconf
      with_items:
          - { file: '/etc/dconf/profile/gdm', regexp: 'user-db', line: 'user-db:user' }
          - { file: '/etc/dconf/profile/gdm', regexp: 'system-db', line: 'system-db:gdm' }
          - { file: '/etc/dconf/profile/gdm', regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }
          - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
          - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: 'banner-message-enable', line: 'banner-message-enable=true' }
          - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: 'banner-message-text', line: "banner-message-text='{{ rhel8cis_warning_banner | replace('\n', ' ') }}' " }
    
    - name: "1.8.3 | Ensure GDM disable-user-list option is enabled"
      block:
        - name: Create /etc/dconf/db/gdm.d directory if it doesn't exist
          file:
            path: /etc/dconf/db/gdm.d
            state: directory
            owner: root
            group: root
            mode: 0755
        - name: Create gdm.custom.conf file with disable-user-list option
          ini_file:
            path: /etc/dconf/db/gdm.d/gdm.custom.conf
            section: org/gnome/gdm
            option: disable-user-list
            value: true
            owner: root
            group: root
            mode: 0644
        - name: Update the dconf database
          command:
            cmd: dconf update

    - name: "1.8.4 | Ensure GDM screen locks when the user is idle"
      block:
        - name: Create /etc/dconf/profile/gdm profile directory if it doesn't exist
          file:
            path: /etc/dconf/profile/gdm
            state: directory
            owner: root
            group: root
            mode: 0755
        - name: Create gdm dconf profile file with lock delay settings
          ini_file:
            path: /etc/dconf/profile/gdm/dconf.profile
            section: system/lockdown
            option: locks
            value: ['org/gnome/desktop/screensaver/lock-delay']
            owner: root
            group: root
            mode: 0644
        - name: Set lock delay value in dconf database
          command:
            cmd: dconf write /org/gnome/desktop/screensaver/lock-delay "180"

    - name: "1.8.5 | Ensure GDM screen locks cannot be overridden"
      block:

      - name: "{{ item.name }}"
        command:
          cmd: "{{ item.cmd }}"
        with_items:
          - { name: "Set screensaver to blank screen after 15 seconds", cmd: "gsettings set org.gnome.desktop.screensaver idle-activation-enabled true" }
          - { name: "Set lock delay to 15 seconds", cmd: "gsettings set org.gnome.desktop.screensaver lock-delay 15" }
          - { name: "Disable Ctrl+Alt+L screen lock", cmd: 'gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver ""' }

      - name: Enable screensaver settings to take effect for all users
        ansible.builtin.ini_file:
          path: /etc/dconf/db/local.d/00-screensaver-settings
          section: system/screensaver
          option: lock-enabled
          value: true
          owner: root
          group: root
          mode: 0644

    # comment 1.8.6 section for workstations ; uncomment 1.8.6 section for servers
    # this works for both 1.8.6 and 1.8.7 and 1.8.8
    # - name: "1.8.6 | 1.8.7 | Ensure automatic mounting of removable media is disabled"
    #   ansible.builtin.lineinfile:
    #       path: /etc/dconf/db/local.d/00-media-automount
    #       regexp: "{{ item.regex }}"
    #       line: "{{ item.line }}"
    #       create: true
    #       owner: root
    #       group: root
    #       mode: 0640
    #   notify: reload dconf
    #   with_items:
    #       - { regex: '\[org\/gnome\/desktop\/media-handling\]', line: '[org/gnome/desktop/media-handling]' }
    #       - { regex: 'automount=', line: 'automount=false' }
    #       - { regex: 'automount-open=', line: 'automount-open=false'}
    #       - { regex: 'autorun-never=', line: 'autorun-never=true'}

    - name: 1.8.9 Ensure GDM autorun-never is not overridden
      command:
        cmd: gsettings set org.gnome.desktop.media-handling autorun false
    - name: Enable disabling autorun settings to take effect for all users
      ini_file:
        path: /etc/dconf/db/local.d/00-removable-media-settings
        section: system/removable-media
        option: autorun
        value: false
        owner: root
        group: root
        mode: 0644
    - name: Disable auto mounting of drives
      command:
        cmd: gsettings set org.gnome.desktop.media-handling automount false
    - name: Ensure disabling auto mounting settings to take effect for all users
      ini_file:
        path: /etc/dconf/db/local.d/00-removable-media-settings
        section: system/removable-media
        option: automount
        value: false
        owner: root
        group: root
        mode: 0644
    - name: Update dconf settings
      command:
        cmd: dconf update

    # XDMCP is inherently insecure
    - name: "1.8.10 | Ensure XDMCP is not enabled"
      ansible.builtin.lineinfile:
        path: /etc/gdm/custom.conf
        regexp: 'Enable=true'
        state: absent
    