# 1.3.1 and 1.3.2 ask for the Use of AIDE for filesystem_integrity checks. 

# Remediation: We use wazuh for our filesystem_integrity checks.

- name: Filesystem integrity check
  become: true
  hosts: rhel
  tasks:
    
    - name: '1.3.1 | PATCH | Ensure wazuh is installed | Install wazuh'
      package: wazuh-agent
      state: present
    
    #- debug: msg="{{ yum_repos.files }}"
    
    - name: 1.2.3 | PATCH | Update yum.repos
      replace:
          name: file
          regexp: "^gpgcheck=0"
          replace: "gpgcheck=1"
      with_items: 
        - "{{ yum_repos.files }}"
      loop_control:
        label: '{{ item.path }}'