- name: 1.6 Mandatory Access Control - 1.6.1 Configure SELinux
  become: yes
  hosts: rhel
  vars:
    file: 
      - /etc/default/grub
      - /etc/selinux/config
  vars_files: 
    - ../../defaults/main.yml
  tasks:

    - name: 1.6.1.1 Ensure SELinux is installed
      package:
        name: "{{ packages_present[0] }}"
        state: present

    - name: 1.6.1.2 Ensure SELinux is not disabled in bootloader configuration
      replace:
        path: "{{ file[0] }}"
        regexp: '(selinux|enforcing)\s*=\s*0\s*'
        replace: ''
      register: selinux_grub_patch
      ignore_errors: true
      notify: grub2cfg 
    
    # this policy is to meet or exceed the default targeted policy.
    - name: 1.6.1.3 Ensure SELinux policy is configured
      selinux:
        conf: "{{ file[1] }}"
        policy: "{{ selinux_policy }}"
        state: enforcing
      when:
        not selinux_disable

    - name: 1.6.1.4 Ensure SELinux mode is not disabled
      selinux:
        conf: "{{ file[1] }}"
        policy: "{{ selinux_policy }}"
        state: enforcing
      when:
        not selinux_disable

    
    - name: 1.6.1.5 Ensure SELinux status is enforcing
      selinux:
        conf: "{{ file[1] }}"
        policy: "{{ selinux_policy }}"
        state: enforcing
      when:
        not selinux_disable

    - name: 1.6.1.6 Ensure no unconfined services exist
      block:
        - name: Find the unconfined services
          shell: ps -eZ | grep unconfined_service_t | egrep -vw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'
          register: rhelcis_1_6_1_6_unconf_services
          failed_when: false
          changed_when: false
    # had trouble with ansible with 1.6.1.6

      #   - name: "1.6.1.6 | Ensure no unconfined services exist | Message on unconfined services"
      #     ansible.builtin.debug:
      #         msg: "Warning!! You have unconfined services: {{ rhelcis_1_6_1_6_unconf_services.stdout_lines }}"
      #     when: rhelcis_1_6_1_6_unconf_services.stdout | length > 0

      #   - name: "1.6.1.6 | Ensure no unconfined services exist | warning count"
      #     ansible.builtin.import_tasks: ../warning_facts.yml
      #     when: rhelcis_1_6_1_6_unconf_services.stdout | length > 0
      # vars:
      #     warn_control_id: '1.6.1.6'

    - name: "1.6.1.7 | Esnure SETroubleshoot is not installed"
      package:
        name: "{{ packages_absent[1] }}"
        state: absent

    - name: "1.6.1.8 | Ensure the MCS Translation Service (mcstrans) is not installed"
      package: 
        name: "{{ packages_absent[2] }}"
        state: absent